# Generated by Django 5.1.6 on 2025-03-26 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('node_type', models.CharField(choices=[('host', 'Host'), ('subdomain', 'Subdomain'), ('service', 'Service'), ('gateway', 'Gateway')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['domain', 'is_active'], name='network_vis_domain_2ef101_idx'), models.Index(fields=['node_type'], name='network_vis_node_ty_066469_idx')],
                'unique_together': {('domain', 'name', 'node_type')},
            },
        ),
        migrations.CreateModel(
            name='NetworkConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('domain', 'Domain Link'), ('service', 'Service Connection'), ('subdomain', 'Subdomain Link'), ('external', 'External Connection')], max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='network_visualization.networknode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='network_visualization.networknode')),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'is_active'], name='network_vis_source__cc5fdd_idx'), models.Index(fields=['target', 'is_active'], name='network_vis_target__c18e28_idx')],
                'unique_together': {('source', 'target', 'connection_type')},
            },
        ),
    ]
