# Generated by Django 5.1.6 on 2025-02-20 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('node_type', models.CharField(choices=[('host', 'Host'), ('subdomain', 'Subdomain'), ('service', 'Service'), ('gateway', 'Gateway')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['domain'], name='network_vis_domain_dc4926_idx'), models.Index(fields=['name'], name='network_vis_name_6793ef_idx'), models.Index(fields=['node_type'], name='network_vis_node_ty_066469_idx')],
            },
        ),
        migrations.CreateModel(
            name='NetworkConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('direct', 'Direct Connection'), ('gateway', 'Gateway Connection'), ('service', 'Service Connection')], max_length=20)),
                ('metadata', models.JSONField(default=dict)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='network_visualization.networknode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='network_visualization.networknode')),
            ],
            options={
                'indexes': [models.Index(fields=['connection_type'], name='network_vis_connect_869321_idx'), models.Index(fields=['is_active'], name='network_vis_is_acti_e2970f_idx')],
                'unique_together': {('source', 'target', 'connection_type')},
            },
        ),
    ]
