# Generated by Django 5.1.6 on 2025-02-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'System Logs',
                'managed': False,
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='PortScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('service', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('open', 'Open'), ('closed', 'Closed'), ('filtered', 'Filtered'), ('unfiltered', 'Unfiltered'), ('error', 'Error'), ('completed', 'Completed')], max_length=50)),
                ('scan_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=50)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP'), ('sctp', 'SCTP')], default='tcp', max_length=10)),
                ('banner', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('scan_type', models.CharField(default='quick', max_length=50)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-scan_date'],
                'indexes': [models.Index(fields=['host', 'port'], name='reconnaissa_host_35850c_idx'), models.Index(fields=['state'], name='reconnaissa_state_5a6866_idx'), models.Index(fields=['scan_date'], name='reconnaissa_scan_da_9cde68_idx'), models.Index(fields=['scan_status'], name='reconnaissa_scan_st_e61d3a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP'), ('sctp', 'SCTP')], default='tcp', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('product', models.CharField(blank=True, max_length=100)),
                ('version', models.CharField(blank=True, max_length=100)),
                ('extra_info', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('web', 'Web Services'), ('database', 'Database Services'), ('mail', 'Mail Services'), ('file_transfer', 'File Transfer'), ('remote_access', 'Remote Access'), ('domain_services', 'Domain Services'), ('monitoring', 'Monitoring'), ('security', 'Security Services'), ('other', 'Other')], max_length=50)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('cpe', models.JSONField(default=list)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-scan_date'],
                'indexes': [models.Index(fields=['host', 'port'], name='reconnaissa_host_85bdfb_idx'), models.Index(fields=['category'], name='reconnaissa_categor_57cfd9_idx'), models.Index(fields=['risk_level'], name='reconnaissa_risk_le_aa684e_idx')],
                'unique_together': {('host', 'port', 'protocol')},
            },
        ),
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('subdomain', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('discovered_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-discovered_date'],
                'indexes': [models.Index(fields=['domain'], name='reconnaissa_domain_8b0cc4_idx'), models.Index(fields=['subdomain'], name='reconnaissa_subdoma_fadd28_idx')],
                'unique_together': {('domain', 'subdomain')},
            },
        ),
    ]
