"""
Django settings for security_automation project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7u1-7x*e*z3&3d#1f1ktuo#zuu6f($58^=yuz=b4n7(n)6w4kl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'network_visualization',
    'automation',
    'reconnaissance.apps.ReconnaissanceConfig',
    'vulnerability.apps.VulnerabilityConfig',
    'reporting.apps.ReportingConfig',
    
]

# Update DATABASES in settings.py
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'TIMEOUT': 20,  # Seconds
        'OPTIONS': {
            'timeout': 20,
            'check_same_thread': False,
        }
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'automation.middleware.AutomationProcessorMiddleware'

]
# OpenVAS Configuration
# In security_automation/settings.py
# Update the OpenVAS configuration section





# Security Settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Session Security
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True

# Rate Limiting
RATELIMIT_ENABLE = True
RATELIMIT_USE_CACHE = 'default'
RATELIMIT_DEFAULT_RATES = ['100/h']  # Default rate limit

# Logging Configuration
# Add this to your settings.py



# Logging Configuration

# Logging Configuration
import os
from pathlib import Path

# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent

# Create logs directory
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)

# ZAP Scanner Configuration
# These settings control the behavior of the OWASP ZAP integration
ZAP_SETTINGS = {
    'API_KEY': 'change_me_please',  # Change this in production
    'HOST': 'localhost',
    'PORT': 8080,
    'TIMEOUT': 300,  # 5 minutes timeout for ZAP operations
    'DEBUG': DEBUG,  # Tie ZAP debug mode to Django's debug setting
    'MAX_RETRIES': 3,  # Maximum number of connection retry attempts
    'RETRY_DELAY': 5,  # Seconds to wait between retries
}

# Logging Configuration
# This defines how the application handles different types of logs
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {module} {process:d} {thread:d} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
        'simple': {
            'format': '[{asctime}] {levelname} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'level': 'DEBUG' if DEBUG else 'INFO',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'debug.log'),
            'formatter': 'verbose',
            'level': 'DEBUG',
        },
        'service_file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'services.log'),
            'formatter': 'verbose',
            'level': 'INFO',
        },
        'error_file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'error.log'),
            'formatter': 'verbose',
            'level': 'ERROR',
        },
        'security_file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'security.log'),
            'formatter': 'verbose',
            'level': 'INFO',
        }
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'reconnaissance': {
            'handlers': ['console', 'service_file', 'error_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'vulnerability': {
            'handlers': ['console', 'service_file', 'error_file', 'security_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'zap': {
            'handlers': ['console', 'service_file', 'error_file', 'security_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': True,
        },
        'scanner': {
            'handlers': ['console', 'service_file', 'error_file', 'security_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': True,
        }
    },
}

ROOT_URLCONF = 'security_automation.urls'

import os

# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Add this line
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'security_automation.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

SECRET_KEY = 'p6IOStJ0i0azQfySy0mSCIht7VouYg9RGggv6iDgI4MQUSgADoTcy7SG2Z4kjDboM6Q'  # Remember to use environment variables in production
DEBUG = True 

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ZAP Settings
ZAP_SETTINGS = {
    'API_KEY': 'change_me_please',
    'HOST': 'localhost',
    'PORT': 8080,
    'TIMEOUT': 300,
    'MAX_RETRIES': 3,
    'SPIDER_TIMEOUT': 600,
    'ACTIVE_SCAN_TIMEOUT': 1200
}
# Nuclei Settings
NUCLEI_SETTINGS = {
    'TEMPLATES_DIR': 'nuclei-templates',
    'RESULTS_DIR': 'nuclei-results',
    'DEFAULT_SEVERITY': 'critical,high,medium',
    'RATE_LIMIT': 150,
    'TIMEOUT': 300,
    'GO_PATH': '/usr/local/go/bin',  # Adjust this based on your Go installation
    'BINARY_PATH': str(Path.home() / "go" / "bin" / "nuclei"),  # Default Go installation path
}

# Email Settings
# Email Settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Changed from example.com to Gmail's SMTP server
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'harmeeksingh729@gmail.com' 
EMAIL_HOST_PASSWORD = 'lyel vzou qbuh fvcl'  # App password or regular password
DEFAULT_FROM_EMAIL = 'harmeeksingh729@gmail.com'  # Should match EMAIL_HOST_USER

AUTOMATION_AUTOSTART = True  # Automatically start the processor on application startup
AUTOMATION_PROCESSING_INTERVAL = 60  # Seconds between processing cycles