# Generated by Django 5.1.6 on 2025-03-24 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
                ('scan_profile', models.CharField(choices=[('quick', 'Quick Scan'), ('standard', 'Standard Scan'), ('full', 'Full Scan')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('notification_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='automation__status_8ce291_idx'), models.Index(fields=['target'], name='automation__target_c3cdf3_idx'), models.Index(fields=['created_at'], name='automation__created_c37106_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('subdomain_enumeration', 'Subdomain Enumeration'), ('port_scanning', 'Port Scanning'), ('service_identification', 'Service Identification'), ('vulnerability_scanning', 'Vulnerability Scanning'), ('network_mapping', 'Network Mapping'), ('report_generation', 'Report Generation')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('dependencies', models.ManyToManyField(blank=True, related_name='dependents', to='automation.scantask')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='automation.scanworkflow')),
            ],
            options={
                'ordering': ['workflow', 'order'],
                'indexes': [models.Index(fields=['workflow', 'status'], name='automation__workflo_f3e149_idx'), models.Index(fields=['task_type'], name='automation__task_ty_45e1a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('workflow_scheduled', 'Workflow Scheduled'), ('workflow_started', 'Workflow Started'), ('workflow_completed', 'Workflow Completed'), ('workflow_failed', 'Workflow Failed'), ('workflow_canceled', 'Workflow Canceled'), ('task_failed', 'Task Failed'), ('critical_vulnerabilities', 'Critical Vulnerabilities'), ('report_ready', 'Report Ready')], max_length=50)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent', models.BooleanField(default=False)),
                ('sent_time', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='automation.scanworkflow')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['notification_type'], name='automation__notific_d39606_idx'), models.Index(fields=['created_at'], name='automation__created_70366b_idx'), models.Index(fields=['sent'], name='automation__sent_c2ebd2_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
                ('scan_profile', models.CharField(choices=[('quick', 'Quick Scan'), ('standard', 'Standard Scan'), ('full', 'Full Scan')], default='standard', max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], max_length=20)),
                ('cron_expression', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notification_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('last_execution', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=20, null=True)),
                ('last_workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule', to='automation.scanworkflow')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='automation__is_acti_a85145_idx'), models.Index(fields=['frequency'], name='automation__frequen_f03081_idx'), models.Index(fields=['target'], name='automation__target_95e7c1_idx')],
            },
        ),
    ]
